Repository asterinas/asterinas, pull requests merged in 2024-10, with the labels that each got.

#1421 Rename tcp_loopback_bw to tcp_loopback_bw_4k
  .github/workflows/benchmark_asterinas.yml
  test/benchmark/lmbench/summary.json
  test/benchmark/lmbench/tcp_loopback_bw_4k/config.json
  test/benchmark/lmbench/tcp_loopback_bw_4k/result_template.json
  test/benchmark/lmbench/tcp_loopback_bw_4k/run.sh
Labels: S-waiting-on-review

#1386 Refactor the lock usages within `RamInode`
  kernel/src/fs/ramfs/fs.rs
Labels: O-test, S-waiting-on-review

#1424 Extract the status of guest VM from its log
  test/benchmark/common/bench_runner.sh
  test/benchmark/common/host_guest_bench_runner.sh
Labels: S-waiting-on-review

#1393 Improve over 10% on lmbench-stat/open/fs by refactoring `Dentry`
  kernel/src/device/pty/mod.rs
  kernel/src/fs/device.rs
  kernel/src/fs/fs_resolver.rs
  kernel/src/fs/inode_handle/dyn_cap.rs
  kernel/src/fs/inode_handle/mod.rs
  kernel/src/fs/path/dentry.rs
  kernel/src/fs/path/mount.rs
  kernel/src/net/socket/unix/addr.rs
  kernel/src/net/socket/unix/ns/path.rs
  kernel/src/process/program_loader/elf/load_elf.rs
  kernel/src/process/program_loader/mod.rs
  kernel/src/syscall/execve.rs
  kernel/src/syscall/mount.rs
  kernel/src/syscall/utimens.rs
Labels: O-test, S-waiting-on-review

#1441 Fix docker image publication
  .github/workflows/publish_docker_images.yml
Labels: S-waiting-on-review

#1454 Bump version to 0.9.3
  .github/workflows/benchmark_asterinas.yml
  .github/workflows/publish_osdk_and_ostd.yml
  .github/workflows/publish_website.yml
  .github/workflows/push_git_tag.yml
  .github/workflows/test_asterinas.yml
  .github/workflows/test_asterinas_vsock.yml
  .github/workflows/test_osdk.yml
  Cargo.lock
  README.md
  README_CN.md
  VERSION
  docs/src/kernel/README.md
  docs/src/kernel/intel_tdx.md
  osdk/Cargo.lock
  osdk/Cargo.toml
  osdk/test-kernel/Cargo.toml
  ostd/Cargo.toml
  ostd/libs/linux-bzimage/boot-params/Cargo.toml
  ostd/libs/linux-bzimage/builder/Cargo.toml
  ostd/libs/linux-bzimage/setup/Cargo.toml
  ostd/libs/ostd-macros/Cargo.toml
  ostd/libs/ostd-test/Cargo.toml
Labels: S-waiting-on-review

#1461 `PROT_WRITE` implies `PROT_READ` on x86
  kernel/src/syscall/mmap.rs
  kernel/src/syscall/mprotect.rs
Labels: P0, S-waiting-on-review

#1478 Treat thread oops with better care to avoid silent panics
  kernel/src/lib.rs
  kernel/src/thread/kernel_thread.rs
  kernel/src/thread/mod.rs
  kernel/src/thread/oops.rs
  kernel/src/thread/task.rs
Labels: P1, O-bugfix, S-waiting-on-review

#1435 Add /proc/[pid]/stat and /proc/[pid]/status
  .typos.toml
  kernel/src/fs/file_table.rs
  kernel/src/fs/procfs/pid/mod.rs
  kernel/src/fs/procfs/pid/stat.rs
  kernel/src/fs/procfs/pid/status.rs
Labels: S-waiting-on-review

#1486 Fix flock lost-wakeup bugs
  kernel/src/fs/utils/flock.rs
Labels: C-bug
