Repository asterinas/asterinas, pull requests merged in 2024-08, with the labels that each got.

#1143 Fix the lmbench-exec/shell error when /tmp exists
  test/benchmark/lmbench-exec/run.sh
  test/benchmark/lmbench-shell/run.sh
Labels: C-bug, S-waiting-on-review

#1118 Optimize trim methods in `Vmar`.
  kernel/aster-nix/src/vm/vmar/mod.rs
  kernel/aster-nix/src/vm/vmar/vm_mapping.rs
Labels: S-waiting-on-review

#1150 Fix lmbench-ctx extraction
  test/benchmark/bench_linux_and_aster.sh
Labels: S-waiting-on-review

#1152 Add boterinas introduction to Asterinas book
  docs/src/SUMMARY.md
  docs/src/to-contribute/boterinas.md
Labels: S-waiting-on-review

#1183 Fix a concurrency bug in clocksource
  kernel/comps/time/src/clocksource.rs
Labels: S-waiting-on-review

#1187 Enhance the stability of lmbench-mem
  test/benchmark/lmbench-mem-fcp/config.json
  test/benchmark/lmbench-mem-fcp/run.sh
  test/benchmark/lmbench-mem-frd/config.json
  test/benchmark/lmbench-mem-frd/run.sh
  test/benchmark/lmbench-mem-fwr/config.json
  test/benchmark/lmbench-mem-fwr/run.sh
Labels: S-waiting-on-review

#1204 Fix compile error due to `lock_irq_disabled`
  ostd/src/arch/x86/iommu/dma_remapping/mod.rs
Labels: O-bugfix, S-waiting-on-review

#1156 Refactor all io APIs of vfs based on `VmReader`/`VmWriter`
  kernel/aster-nix/src/device/null.rs
  kernel/aster-nix/src/device/pty/pty.rs
  kernel/aster-nix/src/device/random.rs
  kernel/aster-nix/src/device/tdxguest/mod.rs
  kernel/aster-nix/src/device/tty/device.rs
  kernel/aster-nix/src/device/tty/mod.rs
  kernel/aster-nix/src/device/urandom.rs
  kernel/aster-nix/src/device/zero.rs
  kernel/aster-nix/src/error.rs
  kernel/aster-nix/src/fs/devpts/ptmx.rs
  kernel/aster-nix/src/fs/devpts/slave.rs
  kernel/aster-nix/src/fs/epoll/epoll_file.rs
  kernel/aster-nix/src/fs/exfat/inode.rs
  kernel/aster-nix/src/fs/exfat/mod.rs
  kernel/aster-nix/src/fs/ext2/impl_for_vfs/inode.rs
  kernel/aster-nix/src/fs/ext2/inode.rs
  kernel/aster-nix/src/fs/file_handle.rs
  kernel/aster-nix/src/fs/inode_handle/dyn_cap.rs
  kernel/aster-nix/src/fs/inode_handle/mod.rs
  kernel/aster-nix/src/fs/inode_handle/static_cap.rs
  kernel/aster-nix/src/fs/pipe.rs
  kernel/aster-nix/src/fs/procfs/template/file.rs
  kernel/aster-nix/src/fs/procfs/template/sym.rs
  kernel/aster-nix/src/fs/ramfs/fs.rs
  kernel/aster-nix/src/fs/utils/inode.rs
  kernel/aster-nix/src/fs/utils/random_test.rs
  kernel/aster-nix/src/net/socket/ip/datagram/mod.rs
  kernel/aster-nix/src/net/socket/ip/stream/mod.rs
  kernel/aster-nix/src/net/socket/unix/stream/socket.rs
  kernel/aster-nix/src/net/socket/vsock/stream/socket.rs
  kernel/aster-nix/src/process/program_loader/elf/load_elf.rs
  kernel/aster-nix/src/process/program_loader/mod.rs
  kernel/aster-nix/src/syscall/eventfd.rs
  kernel/aster-nix/src/syscall/pread64.rs
  kernel/aster-nix/src/syscall/preadv.rs
  kernel/aster-nix/src/syscall/pwrite64.rs
  kernel/aster-nix/src/syscall/pwritev.rs
  kernel/aster-nix/src/syscall/read.rs
  kernel/aster-nix/src/syscall/sendfile.rs
  kernel/aster-nix/src/syscall/write.rs
  kernel/aster-nix/src/vm/vmo/dyn_cap.rs
  kernel/aster-nix/src/vm/vmo/mod.rs
  kernel/aster-nix/src/vm/vmo/static_cap.rs
  kernel/comps/block/src/impl_block_device.rs
  ostd/src/io_mem.rs
  ostd/src/mm/dma/dma_coherent.rs
  ostd/src/mm/dma/dma_stream.rs
  ostd/src/mm/frame/mod.rs
  ostd/src/mm/frame/segment.rs
  ostd/src/mm/io.rs
Labels: O-refactor, S-waiting-on-review

#1247 Update href in benchmark link
  README.md
  README_CN.md
Labels: S-waiting-on-review

#1258 Make the allocated segment uninitialized in the ring buffer (mitigate the performance degradation of `lmbench-unix-connect-latency`)
  kernel/src/util/ring_buffer.rs
Labels: O-test, S-waiting-on-review
